os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
services:
  - redis-server
before_script:
  - sudo redis-server
script:
  - eval "$(curl -sL swift.vapor.sh/ci)"
  - eval "$(curl -sL swift.vapor.sh/codecov)"
